Add Linit page
lugnitdgp/lugnitdgp-website pull request #22
Opened 2018-10-03 22:29 UTC by arc9693

2018-10-04 15:17 UTC, ankan17 requested changes
Add navbar entry for linit

2018-10-04 20:51 UTC, arc9693 commented
Done . @ankan17 Please check.

2018-10-05 13:03 UTC, ankan17 approved these changes

2018-10-05 13:04 UTC, merged

2018-10-05 18:14 UTC, ankan17 commented
@arc9693 Use scoped styling and open another PR